### ISSUE TITLE
Node type doesn't necessarily exist in `no-controller-access-in-routes`

### ISSUE THREAD

**Issue by MikiDi** [ember-cli/eslint-plugin-ember#1282]
Line https://github.com/ember-cli/eslint-plugin-ember/blob/d0a7a739fd94c33897919d7012f105e6e73de233/lib/rules/no-controller-access-in-routes.js#L163 throws in case a variable is declared without assigning (ie `let myVar;`) . Probably introduced by https://github.com/ember-cli/eslint-plugin-ember/pull/1281

Produces a stack-trace looking like this:
```
TypeError: Cannot read property 'type' of null
Occurred while linting /app/app/pods/agenda/agendaitems/agendaitem/documents/route.js:18
    at VariableDeclarator (/app/node_modules/eslint-plugin-ember/lib/rules/no-controller-access-in-routes.js:163:23)
    at /app/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/app/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/app/node_modules/eslint/lib/linter/node-event-generator.js:293:26)
    at NodeEventGenerator.applySelectors (/app/node_modules/eslint/lib/linter/node-event-generator.js:322:22)
    at NodeEventGenerator.enterNode (/app/node_modules/eslint/lib/linter/node-event-generator.js:336:14)
    at CodePathAnalyzer.enterNode (/app/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:711:23)
    at /app/node_modules/eslint/lib/linter/linter.js:960:32
    at Array.forEach (<anonymous>)
```

**Comment by bmish** [comment]
Thanks for the report, will fix shortly.
