### ISSUE TITLE
Does not work with ESLint v8

### ISSUE THREAD

**Issue by boris-petrov** [ember-cli/eslint-plugin-ember#1332]
Updating ESLint to v8 leads to:

```
Oops! Something went wrong! :(

ESLint: 8.0.0

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/util/traverser' is not defined by "exports" in /home/boris/project/node_modules/eslint/package.json
Occurred while linting /home/boris/project/app/app.ts:1
Rule: "ember/require-computed-property-dependencies"
    at new NodeError (node:internal/errors:371:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:440:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:692:3)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (/home/boris/project/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at new getTraverser (/home/boris/project/node_modules/eslint-plugin-ember/lib/utils/traverser.js:12:17)
```

**Comment by bmish** [comment]
I'll look into this soon.
