### ISSUE TITLE
ember/jquery-ember-run throws error when event contains a colon

### ISSUE THREAD

**Issue by runspired** [ember-cli/eslint-plugin-ember#1359]
Error seen below:

```
Oops! Something went wrong! :(

ESLint: 7.32.0

AssertionError [ERR_ASSERTION]: Node must be provided when reporting error if location is not provided
    at assertValidNodeInfo (/Users/runspired/github/private/fnb/frontend/node_modules/eslint/lib/linter/report-translator.js:98:9)
    at /Users/runspired/github/private/fnb/frontend/node_modules/eslint/lib/linter/report-translator.js:332:9
    at Object.report (/Users/runspired/github/private/fnb/frontend/node_modules/eslint/lib/linter/linter.js:926:41)
    at report (/Users/runspired/github/private/fnb/frontend/node_modules/eslint-plugin-ember/lib/rules/jquery-ember-run.js:52:15)
    at checkJqueryCall (/Users/runspired/github/private/fnb/frontend/node_modules/eslint-plugin-ember/lib/rules/jquery-ember-run.js:94:15)
    at Program:exit (/Users/runspired/github/private/fnb/frontend/node_modules/eslint-plugin-ember/lib/rules/jquery-ember-run.js:137:11)
    ```
    
    Triggering Code:
    
    ```js
           $(this).on("select2:open", () => {
              component.nextFocus = later(focusInput, 200);
          });
    ```
    
   This issue goes away if the event does not contain a colon (e.g. `click`) or if the assignment is wrapped in a run loop.

**Comment by johanrd** [comment]
to be specific, i think PR #1431 fixed it
