### ISSUE TITLE
no-capital-letters-in-routes will crash the linter if you use variable

### ISSUE THREAD

**Issue by ysmood** [ember-cli/eslint-plugin-ember#163]
Such as

```js
this.route('create', function () {
  const routeName = 'any';
  this.route(routeName);
});
```

**Comment by SimeonC** [comment]
The error output in this case is:

```
TypeError: Cannot read property 'match' of undefined
    at Linter.CallExpression (.../node_modules/eslint-plugin-ember/lib/rules/no-capital-letters-in-routes.js:28:56)
    at emitOne (events.js:120:20)
    at Linter.emit (events.js:210:7)
    at NodeEventGenerator.applySelector (.../node_modules/eslint/lib/util/node-event-generator.js:265:26)
    at NodeEventGenerator.applySelectors (.../node_modules/eslint/lib/util/node-event-generator.js:294:22)
    at NodeEventGenerator.enterNode (.../node_modules/eslint/lib/util/node-event-generator.js:308:14)
    at CodePathAnalyzer.enterNode (.../node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:602:23)
...
Process finished with exit code -1
```
