### ISSUE TITLE
`no-tracked-properties-from-args` blows up

### ISSUE THREAD

**Issue by boris-petrov** [ember-cli/eslint-plugin-ember#1711]
```
TypeError: Cannot read properties of null (reading 'object')
Occurred while linting /home/boris/project/app/components/some-component.ts:14
Rule: "ember/no-tracked-properties-from-args"
    at visitClassPropertyOrPropertyDefinition (/home/boris/project/node_modules/eslint-plugin-ember/lib/rules/no-tracked-properties-from-args.js:15:16)
    at PropertyDefinition (/home/boris/project/node_modules/eslint-plugin-ember/lib/rules/no-tracked-properties-from-args.js:58:9)
    at ruleErrorHandler (/home/boris/project/node_modules/eslint/lib/linter/linter.js:1115:28)
    at /home/boris/project/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/home/boris/project/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/home/boris/project/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/home/boris/project/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (/home/boris/project/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
    at CodePathAnalyzer.enterNode (/home/boris/project/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:795:23)
```

**Comment by boris-petrov** [comment]
The issue is fixed for me, thanks!
