### ISSUE TITLE
`no-deprecated-router-transition-methods` blows up

### ISSUE THREAD

**Issue by boris-petrov** [ember-cli/eslint-plugin-ember#1728]
```
TypeError: classMembers is not iterable
Occurred while linting /home/boris/project/app/components/some-component.ts:28
Rule: "ember/no-deprecated-router-transition-methods"
    at CallExpression (/home/boris/project/node_modules/eslint-plugin-ember/lib/rules/no-deprecated-router-transition-methods.js:140:37)
    at ruleErrorHandler (/home/boris/project/node_modules/eslint/lib/linter/linter.js:1115:28)
    at /home/boris/project/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/home/boris/project/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/home/boris/project/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/home/boris/project/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (/home/boris/project/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
    at CodePathAnalyzer.enterNode (/home/boris/project/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:795:23)
    at /home/boris/project/node_modules/eslint/lib/linter/linter.js:1150:32
```

That specific line is the `class` line:
```ts
@classic
@tagName('tr')
class SomeComponent extends Intermediary.extend(SomeMixin) {}
```

**Comment by boris-petrov** [comment]
The `ember/no-implicit-injections` also blows up on the same line:

```
TypeError: Cannot read properties of undefined (reading 'reduce')
Occurred while linting /home/boris/project/app/components/some-component.ts:28
Rule: "ember/no-implicit-injections"
    at onModuleFound (/home/boris/project/node_modules/eslint-plugin-ember/lib/rules/no-implicit-injections.js:149:53)
    at CallExpression (/home/boris/project/node_modules/eslint-plugin-ember/lib/rules/no-implicit-injections.js:193:11)
    at ruleErrorHandler (/home/boris/project/node_modules/eslint/lib/linter/linter.js:1115:28)
    at /home/boris/project/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/home/boris/project/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/home/boris/project/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/home/boris/project/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (/home/boris/project/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
    at CodePathAnalyzer.enterNode (/home/boris/project/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:795:23)
```

**Comment by Frank3K** [comment]
Can confirm this report; I encountered the same for `ember/no-implicit-injections`.

Demo file:

```js
import AuthenticatedRouteMixin from 'ember-simple-auth/mixins/authenticated-route-mixin';
import Route from '@ember/routing/route';
import classic from 'ember-classic-decorator';

@classic
export default class DemoRoute extends Route.extend(AuthenticatedRouteMixin) {
	authenticationRoute = 'index';
}
```

**Comment by bmish** [comment]
Hopefully it's fixed in https://github.com/ember-cli/eslint-plugin-ember/releases/tag/v11.4.1? @rtablada

**Comment by Frank3K** [comment]
Thanks for the fix. I'm not sure if it's related, but the rule still does not work 100% unfortunately. I have created a new issue for this: https://github.com/ember-cli/eslint-plugin-ember/issues/1729.
