### ISSUE TITLE
Error in ember/no-array-prototype-extensions after upgrading to 11.4.4

### ISSUE THREAD

**Issue by dagroe** [ember-cli/eslint-plugin-ember#1771]
I am getting an error after upgrading from `11.4.3` to `11.4.4` (also happens with `11.4.6`):

```
ESLint: 8.33.0

TypeError: Cannot read properties of undefined (reading 'type')
Occurred while linting WORKING_DIR/app/components/some-component.ts:121
Rule: "ember/no-array-prototype-extensions"
    at CallExpression (WORKING_DIR/node_modules/eslint-plugin-ember/lib/rules/no-array-prototype-extensions.js:726:36)
    at ruleErrorHandler (WORKING_DIR/node_modules/eslint/lib/linter/linter.js:1118:28)
    at WORKING_DIR/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (WORKING_DIR/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (WORKING_DIR/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (WORKING_DIR/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (WORKING_DIR/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
    at CodePathAnalyzer.enterNode (WORKING_DIR/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:795:23)
    at WORKING_DIR/node_modules/eslint/lib/linter/linter.js:1153:32
```

The error is not specific to some code, e.g. when removing `some-component.ts` it would just appear on the next file.

**Comment by bmish** [comment]
CC: @canrozanes

**Comment by lin-ll** [comment]
Here's a way to reproduce the error:
```
import { A } from '@ember/array';

this.foo = A();
this.foo.toArray();
```
