### ISSUE TITLE
new-modules breaking since 5.0.0

### ISSUE THREAD

**Issue by anehx** [ember-cli/eslint-plugin-ember#183]
Hi,

Since version 5.0.0, the new-modules rule breaks my stuff:

```
TypeError: Cannot read property '1' of undefined
    at populateMessage (/.../node_modules/eslint-plugin-ember/lib/rules/new-module-imports.js:109:20)
    at properties.forEach (/.../node_modules/eslint-plugin-ember/lib/rules/new-module-imports.js:86:25)
    at Array.forEach (<anonymous>)
    at reportNestedProperties (/.../node_modules/eslint-plugin-ember/lib/rules/new-module-imports.js:84:18)
    at VariableDeclarator.properties.forEach (/.../node_modules/eslint-plugin-ember/lib/rules/new-module-imports.js:32:13)
    at Array.forEach (<anonymous>)
    at VariableDeclarator (/.../node_modules/eslint-plugin-ember/lib/rules/new-module-imports.js:27:20)
    at listeners.(anonymous function).forEach.listener (/.../node_modules/eslint/lib/util/safe-emitter.js:47:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/.../node_modules/eslint/lib/util/safe-emitter.js:47:38)
```

I believe, it happens if I'm importing stuff which doesn't have a new import path, e.g.:

```javascript
import Ember from 'ember'

const { Handlebars: { Utils: { escapeExpression } } } = Ember
```

**Comment by jeanduplessis** [comment]
I'm having the same issue. Disabling the new-module-imports rule allows it works again: `'ember/new-module-imports': 'off'`
