### ISSUE TITLE
Error While Linting - new-module-imports

### ISSUE THREAD

**Issue by Alonski** [ember-cli/eslint-plugin-ember#189]
Hey friends,
I just updated to "^5.0.1" from "^4.6.1"

When linting I now get this error (causes Ember Build to also fail):
```
$ eslint app
Cannot read property 'forEach' of undefined
TypeError: Cannot read property 'forEach' of undefined
    at VariableDeclarator (D:\Projects\myApp\node_modules\eslint-plugin-ember\lib\rules\new-module-imports.js:27:27)
    at listeners.(anonymous function).forEach.listener (D:\Projects\myApp\node_modules\eslint\lib\util\safe-emitter.js:47:58)
    at Array.forEach (native)
    at Object.emit (D:\Projects\myApp\node_modules\eslint\lib\util\safe-emitter.js:47:38)
    at NodeEventGenerator.applySelector (D:\Projects\myApp\node_modules\eslint\lib\util\node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (D:\Projects\myApp\node_modules\eslint\lib\util\node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (D:\Projects\myApp\node_modules\eslint\lib\util\node-event-generator.js:294:14)
    at CodePathAnalyzer.enterNode (D:\Projects\myApp\node_modules\eslint\lib\code-path-analysis\code-path-analyzer.js:608:23)
    at Traverser.enter (D:\Projects\myApp\node_modules\eslint\lib\linter.js:956:32)
    at Traverser.__execute (D:\Projects\myApp\node_modules\estraverse\estraverse.js:397:31)
    at Traverser.traverse (D:\Projects\myApp\node_modules\estraverse\estraverse.js:501:28)
```

Seems to fail here:
```js
const properties = node.id.properties;
        // Iterate through the destructured properties and report them
        properties.forEach((item) => {
```
properties is undefined

It might be a problem checking the rule on this file:
```js
import Ember from "ember";
import { WebMethod } from "camilyo/utils/web-method";
import { sUrlShortener } from "camilyo/utils/constants";
const $ = Ember;
const { get, set } = Ember;
/* globals common, goModalHandler */

export default Ember.Controller.extend({
    queryParams: [{ isBlast: "b" }],
    ec: "",
    recentLinks: [],
    senderTitle: "",
    isBlast: false,
    smsCampaignWizard: Ember.inject.controller("sms"),
    canAddTemplate: Ember.computed("user", function() {
        return user.checkPerm("show_sms_templates_manager");
    }),
    socialPagesF: Ember.computed("user", function() {
        if (get(this.user, "socialPages") && get(this.user, "socialPages").facebookPages.length > 0) {
            return true;
        }
        return false;
    }),
    socialPagesT: Ember.computed("user", function() {
        if (get(this.user, "socialPages") && get(this.user, "socialPages").twitterPages.length > 0) {
            return true;
        }
        return false;
    }),
    recentLinksDisplay: Ember.computed("recentLinks", "recentLinks.[]", function() {
        return get(this, "recentLinks")
            .toArray()
            .reverse();
    }),
    popups: Ember.Object.create({
        shortlinkCreate: false,
        shortlinkCreateButtons: []
    }),
    smsbodyText: "",
    showShortLinksInnerTitle: Ember.computed("recentLinks", "recentLinks.[]", function() {
        if (get(this, "recentLinks") && get(this, "recentLinks").length > 0) {
            return true;
        }
        return false;
    }),
    smsBodyTextDisplay: Ember.computed("ec.selectedTemplate.body", "smsbodyText", {
        set: function(key, value) {
            set(this, "smsbodyText", value);
        },
        get: function() {
            return get(this, "smsbodyText") ? get(this, "smsbodyText") : "";
        }
    }),
    smsBodyTextDisplayHtm: Ember.computed("smsbodyText", function() {
        if (get(this, "smsbodyText")) {
            return get(this, "smsbodyText").replace(/\n/g, "<br/>");
        } else {
            return "";
        }
    }),
    actions: {
        linkEdit: function() {
            set(this, "popups.shortlinkCreate", true);
        },
        copyShortLink: function(shortLink) {
            set(this, "smsbodyText", get(this, "smsbodyText") + " " + shortLink);
        },
        shortlinkExit: function() {
            set(this, "popups.shortlinkCreate", false);
        },
        submitLink: function() {
            var that = this;
            var url = $(".shortLinkInput")
                .val()
                .replace("https://", "");

            var wrapPrefix =
                user.domain === "test.com"
                    ? "http://webhook.com"
                    : "sgwebhook" + user.domain;

            var wrappedUrl =
                wrapPrefix +
                "?smsShortLink=true&campaignGuid=" +
                get(that, "smsCampaignWizard.campaignGuid") +
                "&url=" +
                encodeURIComponent(url);

            goModalHandler.showMsgBoxNoButtons({
                msg: get(this, "i18n").t("in-progress-please-wait...")
            });
            WebMethod(
                sUrlShortener,
                "Home/ShorterURL",
                { longUrl: wrappedUrl, ts: new Date().getTime() },
                function(data) {
                    if (data && data.status === true) {
                        goModalHandler.hideModal();
                        var responce = data.url.ShortUrl;
                        if (get(that, "recentLinks").length > 2) {
                            get(that, "recentLinks").removeAt(0, 1);
                        }
                        get(that, "recentLinks").pushObject({
                            orig: $(".shortLinkInput").val(),
                            shortUrl: responce
                        });
                    }
                },
                function() {
                    goModalHandler.hideModal();
                    alert("Error");
                }
            );
        },
        saveTemplate: function() {
            var that = this;
            var model = this.store.createRecord("sms", {
                userId: get(this, "user.userId"),
                body: get(this, "smsbodyText"),
                group: get(this, "ec.selectedTemplate.group")
            });
            model.save().then(function() {
                goModalHandler.showMsgBox({
                    msg: get(that, "i18n").t("template-has-been-saved-successfully") + ".",
                    ok: get(that, "i18n").t("ok")
                });
            });
        }
    }
});
```

When I set the rule to Off in eslintrc I get another error with require-super-in-init

```
"eslint": "v4.2.0"
"ember-cli": "2.12.2",
"ember-cli-eslint": "^4.2.2",
```

**Comment by Alonski** [comment]
It seems the issue was with this:
```
    init: Ember.on("init", function() {
        setInterval(function() {
            if (Ember.$(window).width() < 1040) {
                Ember.$(".listings-management").css("width", Ember.$(window).width());
            } else {
                Ember.$(".listings-management").css("width", "100%");
            }
        }, 1000);
    }),
```
Changing this fixed the issue:
```
    init() {
        this._super(...arguments);
        setInterval(function() {
            if (Ember.$(window).width() < 1040) {
                Ember.$(".listings-management").css("width", Ember.$(window).width());
            } else {
                Ember.$(".listings-management").css("width", "100%");
            }
        }, 1000);
    },
```

I ended up debugging the Node instance running ESLint app and figured this out.

Thanks

**Comment by rwwagner90** [comment]
I'm getting `Cannot read property 'forEach' of undefined` as well now.

**Comment by Alonski** [comment]
@rwwagner90 Any idea what code is causing the error?

**Comment by Turbo87** [comment]
@rwwagner90 can you share the full stack trace and possibly an example snippet that reproduces the issue?

**Comment by dcyriller** [comment]
Thanks @rwwagner90 for the direction... I ran into the same issue with an addon with no `.eslintignore` file. Re-generating the file with `ember init` command fixed the issue. Indeed, eslint was running inside the `dist` directory (with ie9-transpiled files inside)...

To reproduce the issue (though I have to say it's not really standard):
- `ember addon new-addon`
- in `.eslintignore` remove the line about `dist`
- add `ie9` to targets `config/targets.js
- `ember install ember-cli-babel' (to get the ember-cli-babel@7)
- `ember install ember-cli-flash' (<- seems the issue was with this transpiled file: https://github.com/poteto/ember-cli-flash/blob/master/app/initializers/flash-messages.js)
- `yarn build`
- `yarn lint:js`

**Comment by chbonser** [comment]
In case it is helpful to others... I was seeing this same error and stack trace but it was because I needed to add `/electron-out/` to `.eslintignore`
