### ISSUE TITLE
no-on-calls-in-components: Cannot read property 'callee' of undefined

### ISSUE THREAD

**Issue by Turbo87** [ember-cli/eslint-plugin-ember#392]
```
TypeError: Cannot read property 'callee' of undefined
    at isOnCall (/Users/tbieniek/Code/qonto/qonto-js/node_modules/eslint-plugin-ember/lib/rules/no-on-calls-in-components.js:40:28)
    at Array.filter (<anonymous>)
    at CallExpression (/Users/tbieniek/Code/qonto/qonto-js/node_modules/eslint-plugin-ember/lib/rules/no-on-calls-in-components.js:63:71)
    at listeners.(anonymous function).forEach.listener (/Users/tbieniek/Code/qonto/qonto-js/node_modules/eslint/lib/util/safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/tbieniek/Code/qonto/qonto-js/node_modules/eslint/lib/util/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/tbieniek/Code/qonto/qonto-js/node_modules/eslint/lib/util/node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (/Users/tbieniek/Code/qonto/qonto-js/node_modules/eslint/lib/util/node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (/Users/tbieniek/Code/qonto/qonto-js/node_modules/eslint/lib/util/node-event-generator.js:294:14)
    at CodePathAnalyzer.enterNode (/Users/tbieniek/Code/qonto/qonto-js/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:632:23)
```

it looks like the `no-on-calls-in-components` rule is not able to handle `...foo` in components, like:

```js
let foo = { bar: 'baz' };

export default Component.extend({
  ...foo,
});
```

**Comment by rajasegar** [comment]
I think this will be due to the **ExperimentalSpreadProperty** `...foo` does not have any value, and we are trying to read the callee of it resulting in the above mentioned error.

Adding a condition like below in the beginning of the `isOnCall` might solve the problem
```js
    const isOnCall = function (node) {
      if (!node.value) return false;
 ```

@Turbo87  what are your thoughts?

**Comment by Turbo87** [comment]
yep, that sounds reasonable
