### ISSUE TITLE
Error thrown linting const export - new-module-imports

### ISSUE THREAD

**Issue by bendemboski** [ember-cli/eslint-plugin-ember#459]
To reproduce:

```shell
$ ember new lint-error
$ cd lint-error
$ echo 'export const foo = 1;' > foo.js
$ yarn lint:js
```

the result is:

```
TypeError: Cannot read property 'some' of undefined
Occurred while linting /private/tmp/lint-error/foo.js:1
    at isInitImportedFrom (/private/tmp/lint-error/node_modules/eslint-plugin-ember/lib/utils/new-module.js:159:18)
    at VariableDeclarator (/private/tmp/lint-error/node_modules/eslint-plugin-ember/lib/rules/new-module-imports.js:59:44)
    at listeners.(anonymous function).forEach.listener (/private/tmp/lint-error/node_modules/eslint/lib/util/safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/private/tmp/lint-error/node_modules/eslint/lib/util/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/private/tmp/lint-error/node_modules/eslint/lib/util/node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (/private/tmp/lint-error/node_modules/eslint/lib/util/node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (/private/tmp/lint-error/node_modules/eslint/lib/util/node-event-generator.js:294:14)
    at CodePathAnalyzer.enterNode (/private/tmp/lint-error/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:632:23)
    at nodeQueue.forEach.traversalInfo (/private/tmp/lint-error/node_modules/eslint/lib/linter.js:752:32)
error Command failed with exit code 2.
```

The code throwing the exception was introduced [here](https://github.com/ember-cli/eslint-plugin-ember/commit/f7e6c7944a6978701570c72d77cf181007f0ab45#diff-1bd027c84b7deaac0b57ddcfb16732aaR127).

**Comment by bmish** [comment]
Thanks for reporting, will release a patch version as soon as we have a fix.

**Comment by broxsonl** [comment]
Came here to report the same error. It appears to be related to a variable declaration within a nested block (though looking at where in our codebase it's blowing up appears to be an exception being thrown for a variable declaration in of a for loop).

It appears to be this rule throwing: https://eslint.org/docs/rules/no-inner-declarations

We've set a static version for our app for now.

**Comment by bendemboski** [comment]
@broxsonl maybe double-check what you're seeing? That doesn't sound anything like what I reported here. If you look at the stack trace above, it leads to `new-module-imports`, and my repro doesn't have anything to do with nested blocks...

**Comment by dcyriller** [comment]
Thank you @bendemboski for your very precise investigation.

@bmish what do you think of the fix?
